### ISSUE TITLE
Indicators - folders with single indicator, information architecture

### ISSUE THREAD

**Issue by mglowacki100** [inovance/traide-issues-public#19]
1. There is a lot of folders with single indicator. Unless you don't have plans for more indicators in those folders, you should remove unnessary level in hiearchy.

2. Order of indicators within folder (now it looks random to me):
i) first approach - just alphabetic order
ii) second approach - copy order from MT or any other popular trading platform

3. Relative RSI and Stochastic RSI should be close together

**Comment by devjustin** [comment]
1. This is due to how features are derived from indicators. Some indicators, like a moving averages, just return a value of a price. Analyzing the price of a moving average is not too helpful. What is helpful is analyzing the difference between the price of the asset and the price of the moving average- so "how far away is the price from the 200-period simple moving average?" and so we derived features from indicators and feature is "Price - Simple Moving Average". 

This has the downside of being slightly unconventional in the trading world but also opens a lot of opportunities. For example, under the "Simple Moving Average" folder, we can create a bunch of features. For example, the percent difference in price and the moving average or the number of periods that the simple moving average has been below the price. So the hierarchy may cumbersome now but does open a lot of doors down the road for new features.

2. Working on it. It'll be in the next update. Going with number 2. Similar indicators will be grouped together.

3. Number 2 will take care of this.

**Comment by mglowacki100** [comment]
ad.1 There is another solution. Instead of folder in indicators, for let's say SMA, in Indicator setting for SMA: put drop-list with price, price difference etc.

**Comment by devjustin** [comment]
I like that idea. It would require some larger changes, though. Let's get them in the right order for now and we'll make another ticket for the enhancement if that is the direction we want to go.

**Comment by devjustin** [comment]
Indicators are now in alphabetical order except for two: Bollinger Bands and Two Moving Average Cross
