### ISSUE TITLE
"Select existing model" table - indicators

### ISSUE THREAD

**Issue by mglowacki100** [inovance/traide-issues-public#20]
"Select existing model" table - indicators: there is a lot of CMO(CMO), ATR(ATR), ... 
-  ATR should be displayed instead of ATR(ATR) 
- when user hover mouse around ATR there should be baloon-tip Average True Range

In indicators tree, I think better approach is to follow format:
- ATR - Average True Range 

instead of 
- Average True Range (ATR)

Abbreviations are more popular in other parts of UI.

**Comment by devjustin** [comment]
Working on this one. Added to be accomplished in next tasks.

When an indicator/feature is selected, the indicator/feature codes are displayed on the histograms on the Dashboard and in the "Select existing model" table on strategy creation page.

The indicator/features are displayed as: "XXX (YYY)" where XXX is the indicator code and YYY is the feature code. This isn't that user friendly, as the user needs to somehow understand what those codes mean.

The XXX abbreviation is usually something well known or good enough for users to understand (commonly used indicator terms), as XXX is in the parentheses of the indicator name , such as "Simple Moving Average (SMA)", or it's the indicator name itself.

However, YYY is probably harder for the user to understand. It probably makes sense to show the feature name instead of the feature code. In this case, switching to feature name would allow "XXX (YYY)" to show up over the histogram and in the "Select existing model" table as "AROON (Aroon Oscillator)".

Other examples of what'll show above histograms and in the table if YYY is the feature name:
AROON (Aroon Down) - would show when AROONDOWN feature of AROON indicator is chosen
AROON (Aroon Up) - would show when AROONUP feature of AROON indicator is chosen
SMA (SMA Price Difference) - would show when PRICE-SMA feature of SMA indicator is chosen
WILLR (Williams' %R) - would show when WILLR (default) feature of WILLR indicator is chosen**

** Note: Jared, if it's a default feature, then the feature should inherit the indicatorName. That is, display the indicator name as YYY.

**Comment by mglowacki100** [comment]
I see this in this way:
![Uploading traide_indicators.png . . .]()
in almost all cases XXX=YYY.
In this way expression like SMA(SMA) could be interpreted as double smoothing.
What do you mean by feature code? Is it price, price difference or volume depending on context?

**Comment by devjustin** [comment]
It will be the indicator, which is "SMA" and in parenthesis it will have the feature, which is the SMA less the Price of the asset. 

SMA (SMA Price Difference)

The actual calculation is Price - SMA value

**Comment by mglowacki100** [comment]
OK. Now, it is clear.

**Comment by devjustin** [comment]
Fixed on 4/01. Closing issue.
